import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['Dancing Script', 'cursive'],
        body: ['Lato', 'sans-serif'],
        cursive: ['Great Vibes', 'cursive'],
        montserrat: ['Montserrat', 'sans-serif'],
        playfair: ['Playfair Display', 'serif'],
        roboto: ['Roboto', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        lora: ['Lora', 'serif'],
        pacifico: ['Pacifico', 'cursive'],
        oswald: ['Oswald', 'sans-serif'],
        caveat: ['Caveat', 'cursive'],
        cinzel: ['Cinzel Decorative', 'serif'],
        sacramento: ['Sacramento', 'cursive'],
        lobster: ['Lobster', 'display'],
        'indie-flower': ['Indie Flower', 'cursive'],
        pinyon: ['Pinyon Script', 'cursive'],
        fredoka: ['Fredoka', 'sans-serif'],
        italianno: ['Italianno', 'cursive'],
        'special-elite': ['Special Elite', 'system-ui'],
        'rock-salt': ['Rock Salt', 'cursive'],
        'alex-brush': ['Alex Brush', 'cursive'],
        'henny-penny': ['Henny Penny', 'system-ui'],
        parisienne: ['Parisienne', 'cursive'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        romantic: {
          blush: "hsl(var(--blush))",
          rose: "hsl(var(--rose))",
          "deep-rose": "hsl(var(--deep-rose))",
          cream: "hsl(var(--cream))",
          "warm-cream": "hsl(var(--warm-cream))",
          gold: "hsl(var(--gold))",
          "soft-gold": "hsl(var(--soft-gold))",
          "petal-pink": "hsl(var(--petal-pink))",
          "leaf-orange": "hsl(var(--leaf-orange))",
          "leaf-red": "hsl(var(--leaf-red))",
          "midnight-purple": "hsl(var(--midnight-purple))",
          "deep-charcoal": "hsl(var(--deep-charcoal))",
          "muted-crimson": "hsl(var(--muted-crimson))",
          "soft-violet": "hsl(var(--soft-violet))",
          "ember-glow": "hsl(var(--ember-glow))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px hsla(350, 50%, 40%, 0.3)" },
          "50%": { boxShadow: "0 0 40px hsla(350, 50%, 40%, 0.6)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-20px) rotate(5deg)" },
        },
        "scratch-fade": {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 0.8s ease-out forwards",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        float: "float 3s ease-in-out infinite",
        "scratch-fade": "scratch-fade 0.7s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
